# Generated by Django 4.1.7 on 2023-03-02 07:17

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=shop.models.getFilename
                    ),
                ),
                ("discriptions", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "tending",
                    models.BooleanField(default=False, help_text="0-default,1-Tending"),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
