# Generated by Django 4.1.7 on 2023-03-02 07:18

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catagory",
            name="tending",
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("vendor", models.CharField(max_length=150)),
                ("quantity", models.IntegerField()),
                ("orginal_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=shop.models.getFilename
                    ),
                ),
                ("discriptions", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "tending",
                    models.BooleanField(default=False, help_text="0-default,1-Tending"),
                ),
                ("createdat", models.DateTimeField(auto_now_add=True)),
                (
                    "catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.catagory"
                    ),
                ),
            ],
        ),
    ]
