# Generated by Django 4.1.7 on 2023-03-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_catagory_tending_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="orginal_price",
            new_name="original_price",
        ),
    ]
