# Generated by Django 4.1.7 on 2023-03-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_product_tending_product_trending_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product_quantity",
            new_name="product_qty",
        ),
    ]
